In [3]:
!pip install numpy 

In [4]:
import numpy as np

In [5]:
list=[1,2,3,4]

In [6]:
type(list)

list

In [7]:
arr=np.array(list)

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [ ]:
1
2
3
4

In [10]:
arr.size

4

In [13]:
z=np.zeros(10)

In [14]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
z=np.ones(10)

In [16]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#one dimensional array
o=np.array([1,2,3,4])

In [18]:
o

array([1, 2, 3, 4])

In [19]:
o.ndim

1

In [20]:
o.shape

(4,)

In [22]:
#2-d array
x=np.array([[1,2,3],[4,5,6],[7,8,9],[4,9,6]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 9, 6]])

In [24]:
x.ndim

2

In [25]:
x.shape

(4, 3)

In [26]:
#3 d array
x=x.reshape(3,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 4],
        [9, 6]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 2)

In [34]:
x=x.reshape(3,4)

In [35]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 9, 6]])

In [36]:
x.ndim

2

In [37]:
x.shape

(3, 4)

# Indexing

## Accessing 1 d array

In [38]:
arr=np.array([1,2,3,4])

In [39]:
arr[1]

2

In [40]:
arr[1]+arr[2]

5

## Accessing 2d array

In [42]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [43]:
print("2 element in 1 st dim",arr[0,1])

2 element in 1 st dim 2


In [44]:
print("2 element in 2 st dim",arr[1,1])

2 element in 2 st dim 7


In [45]:
print("5 element in 2 st dim",arr[1,4])

5 element in 2 st dim 10


In [46]:
#linspace linspace(start,end,no of values between 0 and 10)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
#identitiy matrix
x=np.eye(3)

In [49]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
x.shape

(3, 3)

In [71]:
np.random.randint(0,50,20)

array([16, 41, 11, 21, 48, 39, 41, 49, 47, 27,  0, 12, 46, 12, 46, 37, 48,
        3, 36,  1])

In [53]:
np.random.rand(3,3)

array([[0.67364256, 0.93494142, 0.85574931],
       [0.75441449, 0.0586438 , 0.3941565 ],
       [0.73920329, 0.14633098, 0.96156465]])

In [54]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [56]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
arr.max()

10

In [58]:
arr.argmax()

9

In [66]:
arr.min()

1

In [74]:
a=np.arange(0,11,2)

## slicing

In [75]:
a

array([ 0,  2,  4,  6,  8, 10])

In [77]:
a[1:3]   #[start value:end value+1]

array([2, 4])

In [78]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [79]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [81]:
a[0:0+1,0:1+1]

array([[1, 2]])

In [82]:
a[0:1,0:2]

array([[1, 2]])

In [83]:
a[0:1,1:3]

array([[2, 3]])

In [ ]:
array([[1, 2, 3],    1 st row   0
       [2, 3, 4],    2 nd row   1
       [4, 5, 6]])    3 rd row  2

       c1  c2 c3 




In [84]:
a[2:3,0:2]

array([[4, 5]])

In [85]:
a[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [86]:
a[1:3,1:3]

array([[3, 4],
       [5, 6]])

In [87]:
a[1:,1:]

array([[3, 4],
       [5, 6]])

In [88]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [89]:
a=np.arange(0,11,2)

In [90]:
a

array([ 0,  2,  4,  6,  8, 10])

In [92]:
a1=np.arange(0,11,2)

In [93]:
c=a+a1

In [94]:
c

array([ 0,  4,  8, 12, 16, 20])

In [95]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [96]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [97]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [98]:
arr

array([1, 2, 3, 4, 5])

In [99]:
x

array([1, 2, 3, 4, 5])

In [100]:
arr[0]=31

In [101]:
arr

array([31,  2,  3,  4,  5])

In [102]:
x

array([1, 2, 3, 4, 5])

In [103]:
z=arr.view()

In [104]:
z

array([31,  2,  3,  4,  5])

In [105]:
arr[1]=45


In [106]:
arr

array([31, 45,  3,  4,  5])

In [107]:
z

array([31, 45,  3,  4,  5])

In [ ]:
create an array 5 *5 whcih should contain from 0 to 24